## Método de jacobi


In [2]:
import numpy as np
import math 
#from math import *

In [11]:
#Se define la matriz T

T=np.array([[0,1/10,-1/5,0],[1/11,0,1/11,-3/11],[-1/5,1/10,0,1/10],[0,-3/8,1/8,0]])
C=np.array([3/5,25/11,-11/10,15/8])
X=np.array([0,0,0,0])

In [12]:
print(T.shape)
print(C.shape)
error=1
while error>0.01: 
    resultado=np.dot(T,X)+C
    print(resultado)
    numerador = np.amax(abs((resultado - X)))
    denominador = np.amax(abs(resultado))
    error = numerador/denominador
    X=resultado
    print("Error: ",error)

(4, 4)
(4,)
[ 0.6         2.27272727 -1.1         1.875     ]
Error:  1.0
[ 1.04727273  1.71590909 -0.80522727  0.88522727]
Error:  0.57682119205298
[ 0.93263636  2.05330579 -1.04934091  1.13088068]
Error:  0.16431877641376524
[ 1.01519876  1.95369576 -0.96810863  0.97384272]
Error:  0.08037994847125665
[ 0.9889913   2.01141473 -1.0102859   1.02135051]
Error:  0.02869570385848171
[ 1.00319865  1.99224126 -0.99452174  0.99443374]
Error:  0.013510798495147403
[ 0.99812847  2.00230688 -1.00197223  1.00359431]
Error:  0.005027012074241982


In [13]:
print("X1=: ","{:^10.6f}".format(resultado[0]))
print("X2=: ","{:^10.6f}".format(resultado[1]))
print("X3=: ","{:^10.6f}".format(resultado[2]))
print("X4=: ","{:^10.6f}".format(resultado[3]))

X1=:   0.998128 
X2=:   2.002307 
X3=:  -1.001972 
X4=:   1.003594 


# Método de Newton

In [8]:
def jacobiano(x):
    j= np.array([[3,x[2]*math.sin(x[1]*x[2]),x[1]*math.sin(x[1]*x[2])],[2*x[0], -162*(x[1]+0.1) ,math.cos(x[2])],[-x[1]*math.exp(-x[0]*x[1]),-x[0]*math.exp(-x[0]*x[1]),20]])
    JInversa= np.linalg.inv(j)
    return JInversa
def Fx(x):
    xk=np.array([3*x[0]-math.cos(x[1]*x[2])-1/2, x[0]**2-81*(x[1]+0.1)**2+math.sin(x[2])+1.06, math.exp(-x[0]*x[1])+20*x[2]+(10*math.pi-3)/3])
    #x1=3*x[0]-cos(x[1]*cos[2])-1/2
    #x2=x[0]**2-81*(x[1]+0.1)**2+sin(x[2])+1.06
    #x3=exp(-x[0]*x[1])+20*x[2]+(10-math.pi-3/3)
    

    #xk=np.array([x1,x2,x3])
    return xk
    

In [9]:
x=np.array([0.1,0.1,-0.1])
error=1
c=0

In [10]:
while error>0.1:
    c+=1
    r = jacobiano(x)
    feval= Fx(x)
    resultado=x-np.dot(r,feval)
    
    numerador = np.amax( abs((resultado - x)))
    denominador = np.amax( abs(resultado))
    error = numerador/denominador
    x=resultado



    print("iteración:",c,"Resultado",resultado)
    #print(r)
print("X1=: ","{:^10.6f}".format(resultado[0]))
print("X2=: ","{:^10.6f}".format(resultado[1]))
print("X3=: ","{:^10.6f}".format(resultado[2]))

iteración: 1 Resultado [ 0.49986967  0.01946685 -0.52152047]
iteración: 2 Resultado [ 0.50001424  0.00158859 -0.52355696]
X1=:   0.500014 
X2=:   0.001589 
X3=:  -0.523557 
